filters:
  authors:
   - KoIvRo
   - BombordiroKrocodilo
  stop_words:
   - реклама
   - ad
   - spam
   - promo
  min_length: 20
  threshold: 100

logger:
  level: INFO
  output: stdout

timeout:
  connect: 3
  read: 3
  write: 3
  pool: 3
