"""001_init

Revision ID: 662967a77aa3
Revises:
Create Date: 2026-03-22 19:16:50.228902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision: str = "662967a77aa3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS chats (
            id BIGINT PRIMARY KEY,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        )
    """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS links (
            id SERIAL PRIMARY KEY,
            url VARCHAR(2083) NOT NULL UNIQUE,
            updated_at TIMESTAMP WITH TIME ZONE
        )
    """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS chats_links (
            chat_id BIGINT NOT NULL,
            link_id INTEGER NOT NULL,
            PRIMARY KEY (chat_id, link_id),
            FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
            FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE
        )
    """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS tags (
            id SERIAL PRIMARY KEY,
            name VARCHAR(64) NOT NULL UNIQUE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
        )
    """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS chats_links_tags (
            chat_id BIGINT NOT NULL,
            link_id INTEGER NOT NULL,
            tag_id INTEGER NOT NULL,
            PRIMARY KEY (chat_id, link_id, tag_id),
            FOREIGN KEY (chat_id, link_id) REFERENCES chats_links(chat_id, link_id) ON DELETE CASCADE,
            FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
        )
    """
    )

    op.execute("CREATE INDEX IF NOT EXISTS idx_links_url ON links(url)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_tag_name ON tags(name)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_chats_links_chat_id ON chats_links(chat_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_chats_links_link_id ON chats_links(link_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_clt_chat_link ON chats_links_tags(chat_id, link_id)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop table chats_links_tags;")
    op.execute("drop table chats_links;")
    op.execute("drop table chats;")
    op.execute("drop table links;")
    op.execute("drop table tags;")
    # ### end Alembic commands ###
